export const SPECIES = [
  "Acacia (Babul)", "Acacia auriculiformis (Earleaf Acacia)", "Acacia mangium (Black Wattle)", "Acer (Maple)", "Acer campestre (Field Maple)", 
  "Acer negundo (Box Elder)", "Acer palmatum (Japanese Maple)", "Acer pseudoplatanus (Sycamore)", "Acer rubrum (Red Maple)", "Acer saccharum (Sugar Maple)", 
  "Adansonia (Baobab)", "Adenanthera pavonina (Red Bead Tree)", "Adina cordifolia (Haldu)", "Aesculus (Buckeye)", "Aesculus hippocastanum (Horse Chestnut)", 
  "Ailanthus excelsa (Tree of Heaven)", "Albizia julibrissin (Silk Tree)", "Albizia lebbeck (Siris)", "Albizia procera (White Siris)", "Albizia saman (Rain Tree)", 
  "Alnus (Alder)", "Alnus glutinosa (Common Alder)", "Alnus incana (Grey Alder)", "Alnus rubra (Red Alder)", "Alstonia scholaris (Devil's Tree)", 
  "Amelanchier (Serviceberry)", "Anacardium occidentale (Cashew)", "Annona muricata (Soursop)", "Annona reticulata (Custard Apple)", "Annona squamosa (Sugar Apple)", 
  "Anthocephalus cadamba (Kadamba)", "Araucaria (Monkey Puzzle Tree)", "Araucaria cunninghamii (Hoop Pine)", "Araucaria heterophylla (Norfolk Island Pine)", "Arbutus unedo (Strawberry Tree)", 
  "Areca catechu (Betel Nut Palm)", "Artocarpus altilis (Breadfruit)", "Artocarpus heterophyllus (Jackfruit)", "Artocarpus incisa (Breadnut)", "Artocarpus lakoocha (Monkey Jack)", 
  "Averrhoa bilimbi (Bilimbi)", "Averrhoa carambola (Starfruit)", "Azadirachta indica (Neem)", "Balanites aegyptiaca (Desert Date)", "Bambusa (Bamboo)", 
  "Banksia (Banksia)", "Barringtonia asiatica (Sea Poison Tree)", "Bauhinia purpurea (Purple Orchid Tree)", "Bauhinia variegata (Kachnar)", "Betula (Birch)", 
  "Betula alleghaniensis (Yellow Birch)", "Betula lenta (Sweet Birch)", "Betula nigra (River Birch)", "Betula papyrifera (Paper Birch)", "Betula pendula (Silver Birch)", 
  "Bischofia javanica (Bishop Wood)", "Bixa orellana (Annatto)", "Bombax ceiba (Red Silk Cotton Tree)", "Borassus flabellifer (Palmyra Palm)", "Boswellia serrata (Indian Frankincense)", 
  "Brachychiton acerifolius (Illawarra Flame Tree)", "Broussonetia papyrifera (Paper Mulberry)", "Bruguiera (Mangrove)", "Butea monosperma (Palash/Flame of the Forest)", "Caesalpinia pulcherrima (Peacock Flower)", 
  "Callistemon (Bottlebrush)", "Callitris (Cypress Pine)", "Calophyllum inophyllum (Alexandrian Laurel)", "Camellia sinensis (Tea Plant)", "Cananga odorata (Ylang Ylang)", 
  "Carica papaya (Papaya)", "Carpinus betulus (European Hornbeam)", "Carpinus caroliniana (American Hornbeam)", "Carya (Hickory)", "Carya illinoinensis (Pecan)", 
  "Carya ovata (Shagbark Hickory)", "Cassia fistula (Amaltas/Golden Shower)", "Cassia grandis (Pink Shower Tree)", "Cassia javanica (Apple Blossom Tree)", "Castanea (Chestnut)", 
  "Castanea dentata (American Chestnut)", "Castanea sativa (Sweet Chestnut)", "Casuarina equisetifolia (Whistling Pine)", "Catalpa bignonioides (Southern Catalpa)", "Catalpa speciosa (Northern Catalpa)", 
  "Cedrus (Cedar)", "Cedrus atlantica (Atlas Cedar)", "Cedrus deodara (Deodar Cedar)", "Cedrus libani (Cedar of Lebanon)", "Ceiba pentandra (Kapok Tree)", 
  "Celtis (Hackberry)", "Celtis occidentalis (Common Hackberry)", "Ceratonia siliqua (Carob)", "Cercidiphyllum (Katsura Tree)", "Cercis canadensis (Eastern Redbud)", 
  "Cercis siliquastrum (Judas Tree)", "Chamaecyparis (False Cypress)", "Chamaecyparis lawsoniana (Lawson's Cypress)", "Chamaecyparis obtusa (Hinoki Cypress)", "Chorisia speciosa (Silk Floss Tree)", 
  "Chrysophyllum cainito (Star Apple)", "Cinnamomum camphora (Camphor Tree)", "Cinnamomum verum (Cinnamon)", "Citrus aurantium (Bitter Orange)", "Citrus limon (Lemon)", 
  "Citrus maxima (Pomelo)", "Citrus reticulata (Mandarin Orange)", "Citrus sinensis (Sweet Orange)", "Cocos nucifera (Coconut)", "Coffea (Coffee Plant)", 
  "Cola acuminata (Kola Nut)", "Colophospermum mopane (Mopane)", "Cordia dichotoma (Indian Cherry)", "Cordia sebestena (Geiger Tree)", "Cornus (Dogwood)", 
  "Cornus florida (Flowering Dogwood)", "Cornus kousa (Kousa Dogwood)", "Corylus (Hazel)", "Corylus avellana (Common Hazel)", "Corylus colurna (Turkish Hazel)", 
  "Corymbia ficifolia (Red-flowering Gum)", "Corymbia maculata (Spotted Gum)", "Crateva religiosa (Garlic Pear Tree)", "Cryptomeria japonica (Japanese Cedar)", "Cunninghamia (China Fir)", 
  "Cupressus (Cypress)", "Cupressus arizonica (Arizona Cypress)", "Cupressus macrocarpa (Monterey Cypress)", "Cupressus sempervirens (Mediterranean Cypress)", "Cycas revoluta (Sago Palm)", 
  "Cydonia oblonga (Quince)", "Dalbergia latifolia (Indian Rosewood)", "Dalbergia sissoo (Sheesham)", "Delonix regia (Gulmohar/Royal Poinciana)", "Dillenia indica (Elephant Apple)", 
  "Diospyros blancoi (Velvet Apple)", "Diospyros kaki (Persimmon)", "Diospyros melanoxylon (Tendu)", "Diospyros virginiana (American Persimmon)", "Dipterocarpus (Keruing)", 
  "Dodonaea viscosa (Hopbush)", "Elaeagnus angustifolia (Russian Olive)", "Elaeis guineensis (African Oil Palm)", "Elaeocarpus ganitrus (Rudraksha)", "Emblica officinalis (Amla)", 
  "Enterolobium cyclocarpum (Elephant-ear Tree)", "Eriobotrya japonica (Loquat)", "Erythrina crista-galli (Cockspur Coral Tree)", "Erythrina variegata (Indian Coral Tree)", "Eucalyptus camaldulensis (River Red Gum)", 
  "Eucalyptus citriodora (Lemon-scented Gum)", "Eucalyptus globulus (Tasmanian Blue Gum)", "Eucalyptus marginata (Jarrah)", "Eucalyptus regnans (Mountain Ash)", "Eugenia uniflora (Surinam Cherry)", 
  "Fagus (Beech)", "Fagus grandifolia (American Beech)", "Fagus sylvatica (European Beech)", "Feronia limonia (Wood Apple)", "Ficus benghalensis (Banyan)", 
  "Ficus benjamina (Weeping Fig)", "Ficus carica (Common Fig)", "Ficus elastica (Rubber Tree)", "Ficus microcarpa (Indian Laurel)", "Ficus racemosa (Gular)", 
  "Ficus religiosa (Peepal)", "Ficus sycomorus (Sycamore Fig)", "Flacourtia indica (Governor's Plum)", "Firmiana simplex (Chinese Parasol Tree)", "Fraxinus (Ash)", 
  "Fraxinus americana (White Ash)", "Fraxinus excelsior (European Ash)", "Fraxinus nigra (Black Ash)", "Fraxinus pennsylvanica (Green Ash)", "Garcinia cambogia (Malabar Tamarind)", 
  "Garcinia indica (Kokum)", "Garcinia mangostana (Mangosteen)", "Ginkgo biloba (Maidenhair Tree)", "Gleditsia triacanthos (Honey Locust)", "Gliricidia sepium (Quickstick)", 
  "Gmelina arborea (Gamhar)", "Grevillea robusta (Silky Oak)", "Guaiacum officinale (Lignum Vitae)", "Guazuma ulmifolia (Mutamba)", "Gymnocladus dioicus (Kentucky Coffeetree)", 
  "Haematoxylum campechianum (Logwood)", "Haldina cordifolia (Karam)", "Halesia (Snowdrop Tree)", "Hamamelis (Witch Hazel)", "Hardwickia binata (Anjan)", 
  "Hevea brasiliensis (Para Rubber Tree)", "Hibiscus tiliaceus (Sea Hibiscus)", "Hopea parviflora (Ironwood)", "Hura crepitans (Sandbox Tree)", "Hymenaea courbaril (Jatoba)", 
  "Ilex (Holly)", "Ilex aquifolium (European Holly)", "Ilex opaca (American Holly)", "Ilex paraguariensis (Yerba Mate)", "Jacaranda mimosifolia (Blue Jacaranda)", 
  "Juglans (Walnut)", "Juglans cinerea (Butternut)", "Juglans nigra (Black Walnut)", "Juglans regia (Persian Walnut)", "Juniperus (Juniper)", 
  "Juniperus communis (Common Juniper)", "Juniperus virginiana (Eastern Redcedar)", "Khaya (African Mahogany)", "Kigelia africana (Sausage Tree)", "Koelreuteria paniculata (Goldenrain Tree)", 
  "Lagerstroemia indica (Crape Myrtle)", "Lagerstroemia speciosa (Pride of India)", "Larix (Larch)", "Larix decidua (European Larch)", "Larix laricina (Tamarack)", 
  "Laurus nobilis (Bay Laurel)", "Lawsonia inermis (Henna)", "Leucaena leucocephala (Subabul)", "Liquidambar styraciflua (Sweetgum)", "Liriodendron tulipifera (Tulip Tree)", 
  "Litchi chinensis (Lychee)", "Lithocarpus (Stone Oak)", "Macadamia tetraphylla (Macadamia Nut)", "Maclura pomifera (Osage Orange)", "Maduca longifolia (Mahua)", 
  "Magnolia (Magnolia)", "Magnolia grandiflora (Southern Magnolia)", "Magnolia stellata (Star Magnolia)", "Mallotus philippensis (Kamala Tree)", "Malus (Apple)", 
  "Malus domestica (Orchard Apple)", "Malus sylvestris (European Crab Apple)", "Mangifera indica (Mango)", "Manilkara zapota (Sapodilla/Chikoo)", "Melaleuca (Paperbark)", 
  "Melaleuca alternifolia (Tea Tree)", "Melia azedarach (Persian Lilac/Bakain)", "Mesua ferrea (Cobra Saffron)", "Metasequoia glyptostroboides (Dawn Redwood)", "Michelia champaca (Champak)", 
  "Millettia pinnata (Karanja)", "Mimusops elengi (Bacul)", "Moringa oleifera (Drumstick Tree)", "Morus (Mulberry)", "Morus alba (White Mulberry)", 
  "Morus nigra (Black Mulberry)", "Morus rubra (Red Mulberry)", "Murraya koenigii (Curry Tree)", "Musa (Banana Tree)", "Myristica fragrans (Nutmeg)", 
  "Neolamarckia cadamba (Burflower Tree)", "Nothofagus (Southern Beech)", "Nyssa sylvatica (Black Tupelo)", "Ochroma pyramidale (Balsa)", "Olea europaea (Olive)", 
  "Ostrya virginiana (Eastern Hophornbeam)", "Ougeinia oojeinensis (Sandan)", "Palaquium gutta (Gutta-percha)", "Pandanus (Screw Pine)", "Parkia biglandulosa (Badminton Ball Tree)", 
  "Passiflora edulis (Passion Fruit)", "Paulownia tomentosa (Empress Tree)", "Peltophorum pterocarpum (Copperpod)", "Persea americana (Avocado)", "Phoenix dactylifera (Date Palm)", 
  "Phoenix sylvestris (Wild Date Palm)", "Picea (Spruce)", "Picea abies (Norway Spruce)", "Picea glauca (White Spruce)", "Picea mariana (Black Spruce)", 
  "Picea pungens (Colorado Blue Spruce)", "Pinus (Pine)", "Pinus contorta (Lodgepole Pine)", "Pinus halepensis (Aleppo Pine)", "Pinus nigra (Austrian Pine)", 
  "Pinus palustris (Longleaf Pine)", "Pinus pinea (Stone Pine)", "Pinus ponderosa (Ponderosa Pine)", "Pinus radiata (Monterey Pine)", "Pinus roxburghii (Chir Pine)", 
  "Pinus strobus (Eastern White Pine)", "Pinus sylvestris (Scots Pine)", "Pinus taeda (Loblolly Pine)", "Pinus wallichiana (Blue Pine)", "Pistacia vera (Pistachio)", 
  "Pithecellobium dulce (Manila Tamarind)", "Platanus (Sycamore)", "Platanus occidentalis (American Sycamore)", "Platanus orientalis (Oriental Plane)", "Plumeria (Frangipani)", 
  "Plumeria rubra (Red Frangipani)", "Podocarpus (Plum Pine)", "Podocarpus macrophyllus (Yew Plum Pine)", "Pongamia pinnata (Indian Beech)", "Populus (Poplar/Aspen)", 
  "Populus alba (White Poplar)", "Populus deltoides (Eastern Cottonwood)", "Populus nigra (Black Poplar)", "Populus tremula (Eurasian Aspen)", "Populus tremuloides (Quaking Aspen)", 
  "Prosopis cineraria (Khejri)", "Prosopis juliflora (Mesquite)", "Prunus (Cherry/Plum/Peach/Almond)", "Prunus armeniaca (Apricot)", "Prunus avium (Sweet Cherry)", 
  "Prunus cerasifera (Cherry Plum)", "Prunus cerasus (Sour Cherry)", "Prunus domestica (Plum)", "Prunus dulcis (Almond)", "Prunus persica (Peach)", 
  "Prunus serotina (Black Cherry)", "Prunus serrulata (Japanese Cherry)", "Pseudotsuga menziesii (Douglas Fir)", "Psidium guajava (Guava)", "Pterocarpus indicus (Narra)", 
  "Pterocarpus marsupium (Indian Kino Tree)", "Pterocarpus santalinus (Red Sandalwood)", "Punica granatum (Pomegranate)", "Pyrus (Pear)", "Pyrus calleryana (Callery Pear)", 
  "Pyrus communis (European Pear)", "Quercus (Oak)", "Quercus alba (White Oak)", "Quercus coccinea (Scarlet Oak)", "Quercus ilex (Holm Oak)", 
  "Quercus macrocarpa (Bur Oak)", "Quercus palustris (Pin Oak)", "Quercus robur (English Oak)", "Quercus rubra (Red Oak)", "Quercus suber (Cork Oak)", 
  "Quercus virginiana (Southern Live Oak)", "Ravenala madagascariensis (Traveller's Tree)", "Rhus (Sumac)", "Ricinus communis (Castor Bean Plant)", "Robinia pseudoacacia (Black Locust)", 
  "Roystonea regia (Royal Palm)", "Salix (Willow)", "Salix alba (White Willow)", "Salix babylonica (Weeping Willow)", "Salix fragilis (Crack Willow)", 
  "Salix nigra (Black Willow)", "Samanea saman (Monkeypod)", "Sambucus (Elderberry)", "Santalum album (Indian Sandalwood)", "Sapindus mukorossi (Indian Soapberry)", 
  "Sapium sebiferum (Chinese Tallow)", "Saraca asoca (Ashoka Tree)", "Sassafras albidum (Sassafras)", "Schleichera oleosa (Kusum)", "Sciadopitys verticillata (Umbrella Pine)", 
  "Sequoia sempervirens (Coast Redwood)", "Sequoiadendron giganteum (Giant Sequoia)", "Shorea robusta (Sal)", "Spathodea campanulata (African Tulip Tree)", "Spondias dulcis (Ambarella)", 
  "Sterculia foetida (Wild Almond)", "Swietenia macrophylla (Big-leaf Mahogany)", "Swietenia mahagoni (West Indian Mahogany)", "Syagrus romanzoffiana (Queen Palm)", "Syringa (Lilac)", 
  "Syringa vulgaris (Common Lilac)", "Syzygium aromaticum (Clove)", "Syzygium cumini (Jamun)", "Syzygium malaccense (Malay Apple)", "Syzygium samarangense (Wax Apple)", 
  "Tabebuia aurea (Tree of Gold)", "Tabebuia rosea (Rosy Trumpet Tree)", "Tamarindus indica (Tamarind)", "Tamarix (Tamarisk)", "Taxodium distichum (Bald Cypress)", 
  "Taxus (Yew)", "Taxus baccata (European Yew)", "Taxus brevifolia (Pacific Yew)", "Taxus cuspidata (Japanese Yew)", "Tectona grandis (Teak)", 
  "Terminalia arjuna (Arjuna)", "Terminalia bellirica (Bahera)", "Terminalia catappa (Indian Almond)", "Terminalia chebula (Harad)", "Terminalia elliptica (Crocodile Bark Tree)", 
  "Theobroma cacao (Cacao Tree)", "Thuja (Arborvitae)", "Thuja occidentalis (Northern White Cedar)", "Thuja plicata (Western Redcedar)", "Tilia (Linden/Basswood)", 
  "Tilia americana (American Basswood)", "Tilia cordata (Small-leaved Linden)", "Toona ciliata (Red Cedar)", "Trema orientalis (Charcoal Tree)", "Tsuga (Hemlock)", 
  "Tsuga canadensis (Eastern Hemlock)", "Tsuga heterophylla (Western Hemlock)", "Ulmus (Elm)", "Ulmus americana (American Elm)", "Ulmus glabra (Wych Elm)", 
  "Ulmus parvifolia (Chinese Elm)", "Ulmus procera (English Elm)", "Ulmus pumila (Siberian Elm)", "Ulmus rubra (Slippery Elm)", "Vachellia nilotica (Gum Arabic Tree)", 
  "Vitellaria paradoxa (Shea Tree)", "Vitex negundo (Chaste Tree)", "Washingtonia filifera (Desert Fan Palm)", "Washingtonia robusta (Mexican Fan Palm)", "Wrightia tinctoria (Pala Indigo)", 
  "Zanthoxylum armatum (Toothache Tree)", "Zelkova serrata (Japanese Zelkova)", "Ziziphus jujuba (Jujube)", "Ziziphus mauritiana (Indian Jujube)"
].sort();

// Provide utility functions to process them
export const getRandomSpecies = () => SPECIES[Math.floor(Math.random() * SPECIES.length)];
